# Audio Feature Extraction — Emotion Recognition

## Objective
Extract meaningful numerical features from the RAVDESS audio dataset for speech emotion classification.

## Features
- **MFCC:** Captures important characteristics of the audio spectrum.
- **Chroma:** Represents energy across musical pitch classes.
- **Mel Spectrogram:** Represents audio energy across Mel-frequency bands.

## Dataset
- Dataset: RAVDESS
- Audio recordings: 1,440
- Emotion classes: 8
- Actors: 24

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

project_path = "/content/drive/MyDrive/Emotion_Recognition"

print("Project folder exists:", os.path.exists(project_path))

if os.path.exists(project_path):
    print("\nFiles and folders inside:")
    print(os.listdir(project_path))

Project folder exists: True

Files and folders inside:
['Audio_Speech_Actors_01-24.zip', 'processed_data', 'ravdess']

In [ ]:
dataset_path = os.path.join(project_path, "ravdess")

print("Extracted dataset exists:", os.path.exists(dataset_path))

if os.path.exists(dataset_path):
    print("Items inside:", os.listdir(dataset_path)[:10])

Extracted dataset exists: True
Items inside: ['Actor_01', 'Actor_02', 'Actor_04', 'Actor_06', 'Actor_03', 'Actor_05', 'Actor_07', 'Actor_08', 'Actor_09', 'Actor_10']

In [ ]:
import os
import shutil

project_folder = "/content/drive/MyDrive/Emotion_Recognition"
os.makedirs(project_folder, exist_ok=True)


zip_source = "/content/Audio_Speech_Actors_01-24.zip"
zip_destination = os.path.join(
    project_folder, "Audio_Speech_Actors_01-24.zip"
)

if os.path.exists(zip_source):
    if not os.path.exists(zip_destination):
        shutil.copy2(zip_source, zip_destination)
        print("ZIP backup completed!")
    else:
        print("ZIP already exists in Google Drive.")
else:
    print("ZIP not found in Colab storage.")


ravdess_source = "/content/ravdess"
ravdess_destination = os.path.join(project_folder, "ravdess")

if os.path.exists(ravdess_source):
    if not os.path.exists(ravdess_destination):
        shutil.copytree(ravdess_source, ravdess_destination)
        print("RAVDESS dataset backup completed!")
    else:
        print("RAVDESS folder already exists in Google Drive.")
else:
    print("Extracted RAVDESS folder not found.")

ZIP not found in Colab storage.
Extracted RAVDESS folder not found.

In [ ]:
import numpy as np
import os

data_folder = "/content/drive/MyDrive/Emotion_Recognition/processed_data"

X = np.load(os.path.join(data_folder, "features.npy"))
y = np.load(os.path.join(data_folder, "labels.npy"))

print("Features shape:", X.shape)
print("Labels shape:", y.shape)

Features shape: (1440, 180)
Labels shape: (1440,)

In [ ]:
import os

project_path = "/content/drive/MyDrive/Emotion_Recognition"

for root, dirs, files in os.walk(project_path):
    if any(f.endswith(".wav") for f in files):
        print("Audio files found in:", root)
        print("Example:", [f for f in files if f.endswith(".wav")][:3])
        break
else:
    print("No WAV files found directly inside the project folder tree.")

Audio files found in: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_01
Example: ['03-01-04-01-01-01-01.wav', '03-01-03-01-02-01-01.wav', '03-01-05-01-02-02-01.wav']

In [ ]:
import os

project_path = "/content/drive/MyDrive/Emotion_Recognition"

for root, dirs, files in os.walk(project_path):
    wav_files = [f for f in files if f.lower().endswith(".wav")]
    zip_files = [f for f in files if f.lower().endswith(".zip")]

    if wav_files:
        print("WAV folder:", root)
        print("WAV files found:", len(wav_files))

    if zip_files:
        print("ZIP file:", [os.path.join(root, f) for f in zip_files])

ZIP file: ['/content/drive/MyDrive/Emotion_Recognition/Audio_Speech_Actors_01-24.zip']
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_01
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_02
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_04
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_06
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_03
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_05
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_07
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_08
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_09
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_10
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_14
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_11
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_13
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_12
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_18
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_15
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_16
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_17
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_19
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_20
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_22
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_23
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_21
WAV files found: 60
WAV folder: /content/drive/MyDrive/Emotion_Recognition/ravdess/Actor_24
WAV files found: 60

In [ ]:
import shutil
import os

source_folder = "/content/processed_data"

for filename in [
    "features.npy",
    "labels.npy",
    "emotion_features.csv"
]:
    shutil.copy2(
        os.path.join(source_folder, filename),
        os.path.join(drive_folder, filename)
    )

print("All files backed up to Google Drive successfully! 🎉")

FileNotFoundError: [Errno 2] No such file or directory: '/content/processed_data/features.npy'

In [ ]:
import os
from google.colab import drive

drive.mount('/content/drive')

zip_path = "/content/drive/MyDrive/Emotion_Recognition/Audio_Speech_Actors_01-24.zip"

print("ZIP file exists:", os.path.exists(zip_path))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
ZIP file exists: True

In [ ]:
import zipfile
import os

extracted_path = "/content/ravdess"

if not os.path.exists(extracted_path):
    with zipfile.ZipFile(zip_path, "r") as zip_ref:
        zip_ref.extractall(extracted_path)

print("Dataset extraction completed!")
print("Dataset path:", extracted_path)
print("Folders:", os.listdir(extracted_path)[:10])

Dataset extraction completed!
Dataset path: /content/ravdess
Folders: ['Actor_09', 'Actor_16', 'Actor_11', 'Actor_02', 'Actor_06', 'Actor_03', 'Actor_12', 'Actor_05', 'Actor_22', 'Actor_10']

In [ ]:
import glob

audio_files = glob.glob(
    os.path.join(extracted_path, "**", "*.wav"),
    recursive=True
)

print("Total audio files:", len(audio_files))
print("Sample path:", audio_files[0] if audio_files else "No files found")

Total audio files: 1440
Sample path: /content/ravdess/Actor_09/03-01-02-01-01-01-09.wav

In [ ]:
import numpy as np
import pandas as pd
import librosa
import matplotlib.pyplot as plt

print("All libraries imported successfully!")

All libraries imported successfully!

In [ ]:
emotion_mapping = {
    "01": "neutral",
    "02": "calm",
    "03": "happy",
    "04": "sad",
    "05": "angry",
    "06": "fearful",
    "07": "disgust",
    "08": "surprised"
}

data = []

for file_path in audio_files:
    filename = os.path.basename(file_path)
    parts = filename.split("-")

    emotion_code = parts[2]
    actor = parts[6].split(".")[0]

    data.append({
        "file_path": file_path,
        "emotion_code": emotion_code,
        "emotion": emotion_mapping[emotion_code],
        "actor": int(actor)
    })

df = pd.DataFrame(data)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (1440, 4)

,file_path,emotion_code,emotion,actor
0,/content/ravdess/Actor_09/03-01-02-01-01-01-09...,02,calm,9
1,/content/ravdess/Actor_09/03-01-08-01-02-01-09...,08,surprised,9
2,/content/ravdess/Actor_09/03-01-06-02-01-02-09...,06,fearful,9
3,/content/ravdess/Actor_09/03-01-07-02-01-02-09...,07,disgust,9
4,/content/ravdess/Actor_09/03-01-07-01-01-02-09...,07,disgust,9

Extracting features from one audio file first

MFCC (40): captures characteristics of the voice and its sound quality.



Chroma (12): captures pitch-class energy information.



Mel spectrogram (128): captures how sound energy is distributed across Mel-frequency bands.

In [ ]:
def extract_features(file_path):
    audio, sample_rate = librosa.load(
        file_path,
        sr=22050,
        mono=True
    )

    mfcc = librosa.feature.mfcc(
        y=audio, sr=sample_rate, n_mfcc=40
    )

    chroma = librosa.feature.chroma_stft(
        y=audio, sr=sample_rate
    )

    mel = librosa.feature.melspectrogram(
        y=audio, sr=sample_rate, n_mels=128
    )

    features = np.concatenate([
        np.mean(mfcc, axis=1),
        np.mean(chroma, axis=1),
        np.mean(mel, axis=1)
    ])

    return features

In [ ]:
sample_features = extract_features(audio_files[0])

print("Feature vector shape:", sample_features.shape)
print("Total features:", len(sample_features))
print("First 10 features:", sample_features[:10])

Feature vector shape: (180,)
Total features: 180
First 10 features: [-760.9573      70.84682     14.50941     19.895678    16.550034
    6.37646     -3.3023164   -2.0840952    3.5492299    2.0649686]

In [ ]:
import time

features_list = []
labels = []

start_time = time.time()

for i, row in enumerate(df.itertuples(index=False), start=1):
    try:
        features = extract_features(row.file_path)

        features_list.append(features)
        labels.append(row.emotion)

    except Exception as e:
        print(f"Error processing {row.file_path}: {e}")

    if i % 100 == 0:
        print(f"Processed {i}/{len(df)} audio files")

end_time = time.time()

print("\nFeature extraction completed!")
print("Successfully processed:", len(features_list))
print("Total labels:", len(labels))
print("Time taken:", round(end_time - start_time, 2), "seconds")

Processed 100/1440 audio files
Processed 200/1440 audio files
Processed 300/1440 audio files
Processed 400/1440 audio files
Processed 500/1440 audio files
Processed 600/1440 audio files
Processed 700/1440 audio files
Processed 800/1440 audio files
Processed 900/1440 audio files
Processed 1000/1440 audio files
Processed 1100/1440 audio files
Processed 1200/1440 audio files
Processed 1300/1440 audio files
Processed 1400/1440 audio files

Feature extraction completed!
Successfully processed: 1440
Total labels: 1440
Time taken: 94.21 seconds

In [ ]:
X = np.array(features_list)
y = np.array(labels)

print("Feature matrix shape:", X.shape)
print("Label array shape:", y.shape)
print("Unique emotions:", np.unique(y))
print("Missing values:", np.isnan(X).sum())

Feature matrix shape: (1440, 180)
Label array shape: (1440,)
Unique emotions: ['angry' 'calm' 'disgust' 'fearful' 'happy' 'neutral' 'sad' 'surprised']
Missing values: 0

In [ ]:
import os

os.makedirs("/content/processed_data", exist_ok=True)

np.save("/content/processed_data/features.npy", X)
np.save("/content/processed_data/labels.npy", y)

print("Features and labels saved successfully!")

Features and labels saved successfully!

In [ ]:
feature_columns = [
    f"feature_{i+1}" for i in range(X.shape[1])
]

features_df = pd.DataFrame(X, columns=feature_columns)
features_df["emotion"] = y

features_df.to_csv(
    "/content/processed_data/emotion_features.csv",
    index=False
)

print("CSV saved successfully!")
print("CSV shape:", features_df.shape)
features_df.head()

CSV saved successfully!
CSV shape: (1440, 181)

,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,...,feature_172,feature_173,feature_174,feature_175,feature_176,feature_177,feature_178,feature_179,feature_180,emotion
0,-760.957275,70.846817,14.509410,19.895678,16.550034,6.376460,-3.302316,-2.084095,3.549230,2.064969,...,0.000005,0.000005,0.000006,0.000004,0.000003,0.000005,0.000003,0.000001,1.702194e-07,calm
1,-728.304749,79.305359,14.432840,25.582109,17.956478,5.968206,3.252356,-0.679589,4.222052,2.164092,...,0.000007,0.000008,0.000007,0.000011,0.000016,0.000013,0.000006,0.000003,1.734669e-07,surprised
2,-694.769409,55.743496,3.966781,23.680119,17.474354,2.295081,-3.281505,1.607771,-0.511379,-1.288448,...,0.000018,0.000031,0.000050,0.000048,0.000044,0.000025,0.000019,0.000007,4.958899e-07,fearful
3,-660.546875,74.531807,-0.118715,21.378948,11.625083,-4.646708,-2.115626,0.513758,-3.935818,-3.973721,...,0.000012,0.000008,0.000010,0.000014,0.000015,0.000008,0.000006,0.000005,6.547123e-07,disgust
4,-730.176758,77.216537,-6.209063,19.956032,13.543464,-3.902761,-7.191379,-7.107752,-0.101063,0.191904,...,0.000002,0.000002,0.000003,0.000003,0.000003,0.000004,0.000003,0.000002,1.158311e-07,disgust

In [ ]:
import librosa
import numpy as np

def extract_improved_features(file_path):
    audio, sr = librosa.load(file_path, sr=22050, mono=True)

    # 1. MFCC features
    mfcc = librosa.feature.mfcc(
        y=audio, sr=sr, n_mfcc=40
    )

    # 2. Chroma features
    chroma = librosa.feature.chroma_stft(
        y=audio, sr=sr, n_chroma=12
    )

    # 3. Mel-spectrogram features
    mel = librosa.feature.melspectrogram(
        y=audio, sr=sr, n_mels=128
    )

    # Calculate mean and standard deviation
    features = np.concatenate([
        np.mean(mfcc, axis=1),
        np.std(mfcc, axis=1),

        np.mean(chroma, axis=1),
        np.std(chroma, axis=1),

        np.mean(mel, axis=1),
        np.std(mel, axis=1)
    ])

    return features

print("Improved feature extraction function created!")

Improved feature extraction function created!

In [ ]:
import os
import pandas as pd

dataset_path = "/content/ravdess"

file_paths = []

for actor_folder in os.listdir(dataset_path):
    actor_path = os.path.join(dataset_path, actor_folder)

    if os.path.isdir(actor_path):
        for file_name in os.listdir(actor_path):
            if file_name.endswith(".wav"):
                file_paths.append(os.path.join(actor_path, file_name))

print("Total audio files:", len(file_paths))

Total audio files: 1440

In [ ]:
sample_path = df.iloc[0]["file_path"]

sample_features = extract_improved_features(sample_path)

print("Feature vector shape:", sample_features.shape)
print("Number of features:", len(sample_features))

Feature vector shape: (360,)
Number of features: 360

In [ ]:
import time
import numpy as np

improved_features_list = []
improved_labels = []

start_time = time.time()

for i, row in enumerate(df.itertuples(index=False), start=1):
    try:
        features = extract_improved_features(row.file_path)

        improved_features_list.append(features)
        improved_labels.append(row.emotion)

    except Exception as e:
        print(f"Error processing {row.file_path}: {e}")

    if i % 100 == 0:
        print(f"Processed {i}/{len(df)} audio files")

X_improved = np.array(improved_features_list)
y_improved = np.array(improved_labels)

print("\nFeature extraction complete!")
print("Features shape:", X_improved.shape)
print("Labels shape:", y_improved.shape)
print(f"Time taken: {time.time() - start_time:.2f} seconds")

Processed 100/1440 audio files
Processed 200/1440 audio files
Processed 300/1440 audio files
Processed 400/1440 audio files
Processed 500/1440 audio files
Processed 600/1440 audio files
Processed 700/1440 audio files
Processed 800/1440 audio files
Processed 900/1440 audio files
Processed 1000/1440 audio files
Processed 1100/1440 audio files
Processed 1200/1440 audio files
Processed 1300/1440 audio files
Processed 1400/1440 audio files

Feature extraction complete!
Features shape: (1440, 360)
Labels shape: (1440,)
Time taken: 86.66 seconds

In [ ]:
import os
import pandas as pd
import numpy as np

save_folder = "/content/drive/MyDrive/Emotion_Recognition/processed_data"
os.makedirs(save_folder, exist_ok=True)

np.save(
    os.path.join(save_folder, "features_improved.npy"),
    X_improved
)

np.save(
    os.path.join(save_folder, "labels_improved.npy"),
    y_improved
)

print("Improved features saved successfully!")
print("Features:", X_improved.shape)
print("Labels:", y_improved.shape)

Improved features saved successfully!
Features: (1440, 360)
Labels: (1440,)